title: "Xuhang Dai"
description: "Computational Chemistry | AI for Drug Discovery | Topological Deep Learning"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
author:
  name: "Xuhang Dai"
  avatar: "xuhangdai.jpg"
  bio: "Ph.D. Candidate | Computational Chemistry | NYU"
  location: "New York, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:xd638@nyu.edu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/XDaiNYU"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=Vx02CkcAAAAJ"
